-- ============================================================
-- PIC21 - data.sql
-- Los datos iniciales (admin) son creados por
-- DataInitializer.java usando el PasswordEncoder de Spring.
-- Este archivo se deja vacío intencionalmente.
-- ============================================================
